const Menu ={ productItems: [
    {
        id: 1,
        image: "assets/pavbhaji.png",
        price: "50",
        category: "North Indian Specials",
        title: "Pav Bhaji",
        selected: false,
    }
    ,
    {
        id: 2,
        image: "assets/cholebature.png",
        price: "50",
        category: "North Indian Specials",
        title: "Chole Bhatoora",
        selected: false,
    },

    {
        id: 3,
        image: "assets/alooparatha.png",
        price: "50",
        category: "Parathas",
        title: "Aloo Paratha",
        selected: false,
    },
    {
        id: 4,
        image: "assets/samosa.png",
        price: "10",
        category: "Snacks",
        title: "Samosa",
        selected: false,
    },
    {
        id: 5,
        image: "assets/uttapam.png",
        price: "60",
        category: "South Indian Specials",
        title: "Uttapam",
        selected: false,
    },
    {
        id: 6,
        image: "assets/masaladosa.png",
        price: "50",
        category: "South Indian Specials",
        title: "Masala Dosa",
        selected: false,
    },
    {
        id: 7,
        image: "assets/vegburger.png",
        price: "35",
        category: "Burgers",
        title: "Veg Burger",
        selected: false,
    },
    {
        id: 8,
        image: "assets/masalasan.png",
        price: "30",
        category: "Sandwiches",
        title: "Masala Sandwich",
        selected: false,
    },
    {
        id: 9,
        image: "assets/hotdog.png",
        price: "25",
        category: "Sandwiches",
        title: "Hotdog",
        selected: false,
    },
    {
        id: 10,
        image: "assets/cheeseburger.png",
        price: "50",
        category: "Burgers",
        title: "Cheese Burger",
        selected: false,
    },
    {
        id: 11,
        image: "assets/mosambi.png",
        price: "30",
        category: "Juices",
        title: "Mosambi Juice",
        selected: false,
    },
    {
        id: 12,
        image: "assets/coke.png",
        price: "20",
        category: "Cold Drinks",
        title: "Coca Cola",
        selected: false,
    },
    {
        id: 13,
        image: "assets/plaindosa.png",
        price: "50",
        category: "South Indian Specials",
        title: "plain Dosa",
        selected: false,
    },
    {
        id: 14,
        image: "assets/dahivada.png",
        price: "40",
        category: "Snacks",
        title: "Dahi Vada",
        selected: false,
    },
    {
        id: 15,
        image: "assets/cheesesan.png",
        price: "30",
        category: "Sandwiches",
        title: "Cheese Sandwich",
        selected: false,
    },
    {
        id: 16,
        image: "assets/choletikki.png",
        price: "25",
        category: "Snacks",
        title: "Chole Tikki",
        selected: false,
    },
    {
        id: 17,
        image: "assets/coffee.png",
        price: "15",
        category: "Beverages",
        title: "Coffee",
        selected: false,
    },
    {
        id: 18,
        image: "assets/fanta.png",
        price: "20",
        category: "Cold Drinks",
        title: "Fanta",
        selected: false,
    },
    {
        id: 19,
        image: "assets/gobhiparatha.png",
        price: "50",
        category: "Parathas",
        title: "Gobhi Paratha",
        selected: false,
    },
    {
        id: 20,
        image: "assets/idli.png",
        price: "40",
        category: "South Indian Specials",
        title: "Idli Sambar",
        selected: false,
    },
    {
        id: 21,
        image: "assets/lassi.png",
        price: "25",
        category: "Beverages",
        title: "Lassi",
        selected: false,
    },
    {
        id: 22,
        image: "assets/limca.png",
        price: "20",
        category: "Cold Drinks",
        title: "Limca",
        selected: false,
    },
    {
        id: 23,
        image: "assets/masaladosa.png",
        price: "50",
        category: "South Indian Specials",
        title: "Masala Dosa",
        selected: false,
    }, {
        id: 24,
        image: "assets/maza.png",
        price: "20",
        category: "Cold Drinks",
        title: "Mazza",
        selected: false,
    }, {
        id: 25,
        image: "assets/pine.png",
        price: "30",
        category: "Juices",
        title: "Pineapple Juice",
        selected: false,
    }, {
        id: 26,
        image: "assets/sprite.png",
        price: "20",
        category: "Cold Drinks",
        title: "Sprite",
        selected: false,
    }, {
        id: 27,
        image: "assets/tea.png",
        price: "7",
        category: "Beverages",
        title: "Tea/Chai",
        selected: false,
    }, {
        id: 28,
        image: "assets/thumbsup.png",
        price: "20",
        category: "Cold Drinks",
        title: "Thumbs Up",
        selected: false,
    }, {
        id: 29,
        image: "assets/vadapav.png",
        price: "20",
        category: "Burgers",
        title: "Vada Pav",
        selected: false,
    }, {
        id: 30,
        image: "assets/veggreensan.png",
        price: "30",
        category: "Sandwiches",
        title: "Veg Green Sandwich",
        selected: false,
    },
    {
        id: 31,
        image: "assets/man.png",
        price: "50",
        category: "chinese",
        title: "Manchurian",
        selected: false,
    },
    {
        id: 32,
        image: "assets/noodle.png",
        price: "50",
        category: "chinese",
        title: " Veg Noodles",
        selected: false,
    },
    {
        id: 33,
        image: "assets/friedrice.png",
        price: "50",
        category: "chinese",
        title: "Fried Rice",
        selected: false,
    },
]}

export default Menu